// Real derived data from the report archive — Yesterday's Calls and Watchlist Drift.
// Generated by unidesk/run_derive_realtime.py from the two most recent tonight_*.json reports.
// Wired 2026-09-01 — replaces the illustrative fixture rows.
import derivedJson from "./report_derived_2026-08-31.json";

export interface DerivedYesterdayCall {
  symbol: string;
  setupType: string;
  date: string;
  entry: number;
  outcome: "hit_target" | "stopped_out" | "unresolved";
  rMultiple: number | null;
  mfePct: number | null;
  maePct: number | null;
  netBps: number | null;
  stopHit: boolean | null;
  gapThrough: boolean | null;
  note: string;
}

export interface DerivedWatchlistEntry {
  symbol: string;
  note: string;
  spark: number[];
  score: number;
  close: number;
  trigger: number | null;
  invalidation: number | null;
}

interface RawDerived {
  report_date: string;
  prior_date: string;
  yesterday_calls: DerivedYesterdayCall[];
  watchlist_drift: DerivedWatchlistEntry[];
  n_prior_candidates: number;
  n_resolved: number;
  n_unresolved: number;
}

const RAW = derivedJson as unknown as RawDerived;

export const REAL_YESTERDAYS_CALLS: DerivedYesterdayCall[] = RAW.yesterday_calls;
export const REAL_WATCHLIST_DRIFT: DerivedWatchlistEntry[] = RAW.watchlist_drift;
export const DERIVED_META = {
  reportDate: RAW.report_date,
  priorDate: RAW.prior_date,
  nPriorCandidates: RAW.n_prior_candidates,
  nResolved: RAW.n_resolved,
  nUnresolved: RAW.n_unresolved,
};